export const actionTypes = {
  LOGIN_ACTION: 'LOGIN',
  EDIT_PROFILE_ACTION: 'EDIT_PROFILE',
  LOGOUT_ACTION: 'LOGOUT',

  FETCH_DONE_ACTION: 'FETCH_DONE',

  LOAD_COURSES_ACTION: 'LOAD_COURSES',
  ADD_COURSE_ACTION: 'ADD_COURSE',

  LOAD_ENROLMENTS_ACTION: 'LOAD_ENROLMENTS',
  ENROL_COURSE_ACTION: 'ENROL_COURSE',
  SET_ENROLCOUNT_ACTION: 'SET_ENROLCOUNT',
  GET_ENROLCOUNT_ACTION: 'FETCH_ENROLCOUNT',

  LOAD_FACE_PHOTOS_ACTION: 'LOAD_FACE_PHOTOS',

  LOAD_ATTENDANCES_ACTION: 'LOAD_ATTENDANCES',
  ADD_ATTENDANCE_ACTION: 'ADD_ATTENDANCE',
  RESET_STATE_ACTION: 'RESET_STATE',
};
